import React, { useState } from 'react'
import { DataGrid } from '@mui/x-data-grid'
import axios from "axios";
// import Promise from 'bluebird'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const columns = [
  { field: 'id', headerName: 'ID', width: 150 },
  { field: 'color', headerName: 'Color', width: 150 },
  { field: 'price', headerName: 'Price', width: 150 },
];

export default function Home() {
  const [cnt, setCnt] = useState(0);
  const [data, setData] = useState([]);

  const generate = () => {
    let newData = [];
    for (let i = 0; i < cnt; ++i) {
      newData.push({ id: Date.now() + i });
      setData(newData);
    }
  }

  const purchase = async () => {
    let newData = [...data]
    console.log('current data:', newData)
    // await Promise.all(
    //   data.map(async curDat => {
    //     // setTimeout(async () => {
    //     //   const dat = await axios.post('http://localhost:3000/api/purchase', curDat)
    //     //   if (!!dat.data.id) {
    //     //     // newData.push(dat.data)
    //     //     // setData(newData)
    //     //   }
    //     // }, 500)
    //     await setTimeout(function () { console.log('test') }, 500)
    //   })
    // )
    const delay = ms => new Promise(resolve => setTimeout(resolve, ms));

    for (let i = 0, p = Promise.resolve(); i < data.length; i++) {
      p = p.then(() => delay(100))
        .then(async () => {
          const dat = await axios.post('http://localhost:3000/api/purchase', data[i])
          console.log('data:', dat.data)
          if (!!dat.data.id) {
            newData[i] = { ...dat.data }
            setData([...newData])
            // newData.push(dat.data)
            // setData(newData)
          }
          console.log(i)
        });
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Test
        </h1>
        <h3>
          <a className={styles.myheading} href='/statistics'>Statistics</a>
        </h3>

        <input type='number' value={cnt} onChange={e => setCnt(e.target.value)} />
        <button onClick={e => generate()}>Generate</button>
        <button onClick={e => purchase()}>Purchase</button>
        <div style={{ height: 400, width: '100%' }}>
          <DataGrid
            rows={data}
            columns={columns}
            pageSize={5}
            rowsPerPageOptions={[5]}
          />
        </div>
      </main>
    </div>
  )
}
