import React, { useState, useEffect } from 'react'
import { DataGrid } from '@mui/x-data-grid'
import { Table, TableContainer, TableHead, TableBody, TableRow, TableCell } from '@mui/material'
import axios from "axios";
// import Promise from 'bluebird'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const columns = [
  { field: 'id', headerName: 'ID', width: 200 },
  { field: 'color', headerName: 'Color', width: 200 },
  { field: 'price', headerName: 'Price', width: 200 },
];

const colorColumns = [
  { field: 'color', headerName: 'Color', width: 200 },
  { field: 'count', headerName: 'Count', width: 200 }
];

const priceColumns = [
  { field: 'price', headerName: 'Price', width: 200 },
  { field: 'count', headerName: 'Count', width: 200 }
];

export default function Statistics() {
  const [data, setData] = useState([]);
  const [color1, setColor1] = useState(0);
  const [color2, setColor2] = useState(0);
  const [color3, setColor3] = useState(0);
  const [price1, setPrice1] = useState(0);
  const [price2, setPrice2] = useState(0);
  const [price3, setPrice3] = useState(0);
  const [price4, setPrice4] = useState(0);
  useEffect(async () => {
    const res = await axios.get('http://localhost:3000/api/purchase')
    const tests = res.data.tests;
    setColor1(tests.filter(test => test.color === '#FF0000').length)
    setColor2(tests.filter(test => test.color === '#00FF00').length)
    setColor3(tests.filter(test => test.color === '#0000FF').length)
    setPrice1(tests.filter(test => test.price === '10').length)
    setPrice2(tests.filter(test => test.price === '20').length)
    setPrice3(tests.filter(test => test.price === '50').length)
    setPrice4(tests.filter(test => test.price === '5').length)
    setData(tests)
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Test
        </h1>
        <h3>
          <a className={styles.myheading} href='/'>Home</a>
        </h3>
        <div style={{ height: 400, width: '100%' }}>
          <DataGrid
            rows={data}
            columns={columns}
            pageSize={5}
            rowsPerPageOptions={[5]}
          />
          <h3>Colors</h3>
          <TableContainer>
            <Table aria-label="sticky table">
              <TableHead>
                <TableRow>
                  {colorColumns.map((column) => (
                    <TableCell
                      key={column.field}
                      align='center'
                      style={{ minWidth: `${column.width}px` }}
                    >
                      {column.headerName}
                    </TableCell>
                  ))}
                </TableRow>
              </TableHead>
              <TableBody>
                <TableRow tabIndex={-1} key='red'>
                  <TableCell key='color' align='center'>
                    Red
                  </TableCell>
                  <TableCell key='cnt' align='center'>
                    {color1}
                  </TableCell>
                </TableRow>
                <TableRow tabIndex={-1} key='green'>
                  <TableCell key='color' align='center'>
                    Green
                  </TableCell>
                  <TableCell key='cnt' align='center'>
                    {color2}
                  </TableCell>
                </TableRow>
                <TableRow tabIndex={-1} key='blue'>
                  <TableCell key='color' align='center'>
                    Blue
                  </TableCell>
                  <TableCell key='cnt' align='center'>
                    {color3}
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </TableContainer>

          <h3>Price</h3>
          <TableContainer>
            <Table aria-label="sticky table">
              <TableHead>
                <TableRow>
                  {priceColumns.map((column) => (
                    <TableCell
                      key={column.field}
                      align='center'
                      style={{ minWidth: `${column.width}px` }}
                    >
                      {column.headerName}
                    </TableCell>
                  ))}
                </TableRow>
              </TableHead>
              <TableBody>
                <TableRow tabIndex={-1} key='red'>
                  <TableCell key='color' align='center'>
                    10
                  </TableCell>
                  <TableCell key='cnt' align='center'>
                    {price1}
                  </TableCell>
                </TableRow>
                <TableRow tabIndex={-1} key='green'>
                  <TableCell key='color' align='center'>
                    20
                  </TableCell>
                  <TableCell key='cnt' align='center'>
                    {price2}
                  </TableCell>
                </TableRow>
                <TableRow tabIndex={-1} key='blue'>
                  <TableCell key='color' align='center'>
                    50
                  </TableCell>
                  <TableCell key='cnt' align='center'>
                    {price3}
                  </TableCell>
                </TableRow>
                <TableRow tabIndex={-1} key='blue'>
                  <TableCell key='color' align='center'>
                    5
                  </TableCell>
                  <TableCell key='cnt' align='center'>
                    {price4}
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </TableContainer>
        </div>
      </main>
    </div>
  )
}
